export default {
  SAVE_UP: "SAVE_UP",
  SAVE_UP_SUCCESS: "SAVE_UP_SUCCESS",
  SAVE_UP_FAILURE: "SAVE_UP_FAILURE",
  GET_UP: "GET_UP",
  GET_UP_SUCCESS: "GET_UP_SUCCESS",
  GET_UP_FAILURE: "GET_UP_FAILURE",
  SAVE_DW: "SAVE_DW",
  SAVE_DW_SUCCESS: "SAVE_DW_SUCCESS",
  SAVE_DW_FAILURE: "SAVE_DW_FAILURE",
  GET_DW: "GET_DW",
  GET_DW_SUCCESS: "GET_DW_SUCCESS",
  GET_DW_FAILURE: "GET_DW_FAILURE",
};
